// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJuF4WMx4xEpl2SkaZzipmBzeN5U1p0wU',
    appId: '1:270049622434:web:3a44f487581133f22c1afb',
    messagingSenderId: '270049622434',
    projectId: 'habitsync-96367',
    authDomain: 'habitsync-96367.firebaseapp.com',
    storageBucket: 'habitsync-96367.firebasestorage.app',
    measurementId: 'G-BGLQGWT2M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGYYlVS4slO50bJqlI80cV5F8GabH9zqI',
    appId: '1:270049622434:android:bf89da3cf3a0b01e2c1afb',
    messagingSenderId: '270049622434',
    projectId: 'habitsync-96367',
    storageBucket: 'habitsync-96367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDziS9-BKhmm4HZshlE-p0dkDTGO5Td-ls',
    appId: '1:270049622434:ios:73aea7d03bd20db52c1afb',
    messagingSenderId: '270049622434',
    projectId: 'habitsync-96367',
    storageBucket: 'habitsync-96367.firebasestorage.app',
    iosBundleId: 'com.example.habitsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDziS9-BKhmm4HZshlE-p0dkDTGO5Td-ls',
    appId: '1:270049622434:ios:73aea7d03bd20db52c1afb',
    messagingSenderId: '270049622434',
    projectId: 'habitsync-96367',
    storageBucket: 'habitsync-96367.firebasestorage.app',
    iosBundleId: 'com.example.habitsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJuF4WMx4xEpl2SkaZzipmBzeN5U1p0wU',
    appId: '1:270049622434:web:f25c4bb6da4c8be62c1afb',
    messagingSenderId: '270049622434',
    projectId: 'habitsync-96367',
    authDomain: 'habitsync-96367.firebaseapp.com',
    storageBucket: 'habitsync-96367.firebasestorage.app',
    measurementId: 'G-39JFRB92GB',
  );
}
